//import 'dart:ui';
import 'package:flutter/material.dart';

//import 'package:flutter/material.dart';
import 'package:get/get.dart';
import '../../core/app_export.dart';

/// Helper class for managing themes and colors.
class ThemeHelper {
  // The current app theme
  final _appTheme = PrefUtils().getThemeData();

// A map of custom color themes supported by the app
  Map<String, PrimaryColors> _supportedCustomColor = {
    'primary': PrimaryColors()
  };

// A map of color schemes supported by the app
  Map<String, ColorScheme> _supportedColorScheme = {
    'primary': ColorSchemes.primaryColorScheme
  };

  /// Changes the app theme to [_newTheme].
  void changeTheme(String _newTheme) {
    PrefUtils().setThemeData(_newTheme);
    Get.forceAppUpdate();
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors _getThemeColors() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedCustomColor.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    return _supportedCustomColor[_appTheme] ?? PrimaryColors();
  }

  /// Returns the current theme data.
  ThemeData _getThemeData() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedColorScheme.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    var colorScheme =
        _supportedColorScheme[_appTheme] ?? ColorSchemes.primaryColorScheme;
    return ThemeData(
      visualDensity: VisualDensity.standard,
      colorScheme: colorScheme,
      textTheme: TextThemes.textTheme(colorScheme),
      scaffoldBackgroundColor: colorScheme.onPrimary,
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          backgroundColor: colorScheme.onPrimary,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(12.0),
          ),
          shadowColor: colorScheme.primary,
          elevation: 14,
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
    );
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors themeColor() => _getThemeColors();

  /// Returns the current theme data.
  ThemeData themeData() => _getThemeData();
}

/// Class containing the supported text theme styles.
class TextThemes {
  static TextTheme textTheme(ColorScheme colorScheme) => TextTheme(
        titleLarge: TextStyle(
          color: appTheme.whiteA700,
          fontSize: 20,
          fontFamily: 'Exo',
          fontWeight: FontWeight.w600,
        ),
        titleMedium: TextStyle(
          color: colorScheme.onPrimary,
          fontSize: 19,
          fontFamily: 'Exo',
          fontWeight: FontWeight.w600,
        ),
      );
}

/// Class containing the supported color schemes.
class ColorSchemes {
  static final primaryColorScheme = ColorScheme.light(
    // Primary colors
    primary: Color(0X19000000),
    primaryContainer: Color(0XFF191D88),
    secondary: Color(0XFF191D88),
    secondaryContainer: Color(0XFF96A7D0),
    tertiary: Color(0XFF191D88),
    tertiaryContainer: Color(0XFF96A7D0),

    // Background colors
    background: Color(0XFF191D88),

    // Surface colors
    surface: Color(0XFF191D88),
    surfaceTint: Color(0XFF191D88),
    surfaceVariant: Color(0XFF96A7D0),

    // Error colors
    error: Color(0XFF191D88),
    errorContainer: Color(0XFF96A7D0),
    onError: Color(0X19000000),
    onErrorContainer: Color(0XFF191D88),

    // On colors(text colors)
    onBackground: Color(0X19000000),
    onInverseSurface: Color(0X19000000),
    onPrimary: Color(0XFF191D88),
    onPrimaryContainer: Color(0X19000000),
    onSecondary: Color(0X19000000),
    onSecondaryContainer: Color(0XFF191D88),
    onTertiary: Color(0X19000000),
    onTertiaryContainer: Color(0XFF191D88),

    // Other colors
    outline: Color(0XFF191D88),
    outlineVariant: Color(0XFF191D88),
    scrim: Color(0XFF191D88),
    shadow: Color(0XFF191D88),

    // Inverse colors
    inversePrimary: Color(0XFF191D88),
    inverseSurface: Color(0XFF191D88),

    // Pending colors
    onSurface: Color(0X19000000),
    onSurfaceVariant: Color(0XFF191D88),
  );
}

/// Class containing custom colors for a primary theme.
class PrimaryColors {
  // BlueGray
  Color get blueGray400 => Color(0XFF888888);

  // Gray
  Color get gray100 => Color(0XFFF4F5F9);

  // White
  Color get whiteA700 => Color(0XFFFFFFFF);
}

PrimaryColors get appTheme => ThemeHelper().themeColor();
ThemeData get theme => ThemeHelper().themeData();
